keys:
  - &rpi5 age1tg9entt4k4uqsw3c4l0wrnvyky8uk5vvpjghrfvw2cd9rjamd44q2vr99v
  - &media-server age1dr2c3lnx9g28a8fynk349ufuvz54t2a28mk7jfzhngn2r8fvc3fq2zw22g
  - &ikovalev age1c0882dc0kj7mwdwud775xerlgk66p439xrlcktlmuv9ed0hfy95sycs699
  - &main-pc age1k56jkzr3frfrlfzdv4uatqqzv8v9h95pgyen9j9v8n67vm7kvvwsd08ghj
  - &pocket4 age1mculuz7alkk7k8at58pq3rf5ktgrutu8psgzmlu0rhycccyjs3nsdrfpec
  - &vm-ru-0 age1jvwlkhhlzjjln5908dj98ft8jg9hj2nju4wmqup2475aw238a3lsnc7y2r
  - &vm-de-0 age1wq77enrcrhe8xa8q7yurgg5lezxzw4xmlx2wyf6cwhrztppsquvqh6yprh

creation_rules:
  - path_regex: secrets/xray-role-entry\.yaml$
    key_groups:
      - age:
        - *ikovalev
        - *vm-ru-0
  - path_regex: secrets/xray-role-exit\.yaml$
    key_groups:
      - age:
        - *ikovalev
        - *vm-de-0
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *rpi5
        - *media-server
        - *ikovalev
        - *main-pc
        - *pocket4
