{
  pkgs,
  nixpkgs-unstable,
  ...
}: {
  environment.systemPackages = with pkgs; [
    neovim
    git
    wl-clipboard
    appimage-run
    gnome-randr
    sunshine
    xorg.libXtst
    xorg.libXi
    firefox-bin
    vscode
    spotify
    gnomeExtensions.touch-x
    telegram-desktop
    vlc
    obs-studio
    jellyfin-media-player
    libreoffice-qt6-fresh
    alacritty
    discord
    solaar
    libnotify
    adwaita-icon-theme
    cinny-desktop
    nixpkgs-unstable.codex
    nixpkgs-unstable.godot
    nodejs
    glow
    nixpkgs-unstable.orca-slicer
  ];
}
